### ISSUE TITLE
User-Specific Properties

### ISSUE THREAD

**Issue by cgarvis** [danscan/rn-redux-mixpanel#13]
[Docs](https://mixpanel.com/docs/managing-users/managing-user_specific-properties)

**Comment by madhums** [comment]
I think these can be set using the `selectUserProfileData` method.

**Comment by madhums** [comment]
I just submitted a PR #14 to set these properties once

**Comment by danscan** [comment]
@madhums Merged your PR.  Sorry– been very busy.  Going to give this repo a much-needed update shortly.

**Comment by madhums** [comment]
Thanks a bunch! :)
