### ISSUE TITLE
Something seems to be broken in 0.17 React Native

### ISSUE THREAD

**Issue by gudmundurmar** [danscan/rn-redux-mixpanel#9]
Has anyone tried to update this to React Native 0.17?
![screen shot 2016-01-21 at 1 29 38 pm](https://cloud.githubusercontent.com/assets/4741365/12481774/4d754f9e-c043-11e5-8a78-06633ed1d46d.png)

**Comment by cgarvis** [comment]
I'm using `1.1.6` with RN `0.18.1` without any problems.  I believe we upgrade to `0.17.0` without problems as well.

**Comment by gudmundurmar** [comment]
@cgarvis Sorry, I forgot about this. I believe the issue was the babel upgrade that made import different because of default export. 
`require('react-native-segment');` changed to `const segment = require('react-native-segment').default;`
It's working fine for me now
